version: '3.8'

services:
  app:
    container_name: libra-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=db
      - DB_PORT=5432
      - DB_NAME=libra_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_POOL_MAX_SIZE=10
      - DB_POOL_MIN_IDLE=5
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: libra-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=libra_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: