spring:
  application:
    name: netcracker-libra
  
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:libra_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      idle-timeout-ms: ${DB_POOL_IDLE_TIMEOUT_MS:300000} # 5 minutes
      connection-timeout-ms: ${DB_POOL_CONN_TIMEOUT_MS:20000} # 20 seconds
      max-lifetime-ms: ${DB_POOL_MAX_LIFETIME_MS:1200000} 
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  
  security:
    basic:
      enabled: true
    filter:
      order: 5
